[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg", "yt-dlp"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install --legacy-peer-deps"]

[deploy]
startCommand = "node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
